version: '3.8'

services:
  web:
    image: image1:latest
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
